# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-20 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repayitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaydate', models.CharField(max_length=32)),
                ('repaymoney', models.CharField(max_length=128)),
                ('repaytype', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='cycletype',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repayitem',
            name='thiscontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contract'),
        ),
    ]
