# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-20 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160418_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('client_name', models.CharField(max_length=128)),
                ('client_idcard', models.CharField(max_length=128)),
                ('bank', models.CharField(max_length=128)),
                ('bank_card', models.CharField(max_length=128)),
                ('money', models.CharField(max_length=128)),
                ('startdate', models.CharField(max_length=32)),
                ('enddata', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='loginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1024)),
                ('thisuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.users')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('thisfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.field')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rate', models.CharField(max_length=16)),
                ('closedtype', models.CharField(max_length=16)),
                ('closedperiod', models.IntegerField()),
                ('repaycycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cycle')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='thisparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party'),
        ),
        migrations.AddField(
            model_name='contract',
            name='thismanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.manager'),
        ),
        migrations.AddField(
            model_name='contract',
            name='thisproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
    ]
